const content = [
  "# OKKY 바이브 코딩 해카톤 llms.txt",
  "",
  "본 문서는 LLM이 해카톤 운영 정보를 정확히 이해하도록 제공하는 고정 텍스트입니다.",
  "기본 사이트: https://vibecoding.okky.kr",
  "문서 인덱스: https://vibecoding.okky.kr/docs",
  "",
  "## 행사 기본소개",
  "",
  "OKKY AI 바이브 코딩 해카톤은 참가자가 문제를 직접 정의하고, AI를 활용해 구현과 배포까지 완주하는 실전형 빌드 행사입니다.",
  "핵심 방향은 완벽한 결과보다 빠른 실행과 학습이며, 아이디어를 제품 형태로 검증 가능한 수준까지 만드는 것을 목표로 합니다.",
  "",
  "핵심 참조 문서:",
  "- 개요: https://vibecoding.okky.kr/docs/overview",
  "- 일정: https://vibecoding.okky.kr/docs/schedule",
  "- 규칙: https://vibecoding.okky.kr/docs/rules",
  "- 공정성 가이드: https://vibecoding.okky.kr/docs/fairness-guide",
  "- 행동강령: https://vibecoding.okky.kr/docs/code-of-conduct",
  "",
  "행사 일정 요약:",
  "- 행사일: 2026-02-21 (토)",
  "- 권장 타임라인: 12:30 체크인 시작, 13:00 오프닝, 18:30 이후 마무리",
  "- 운영 상황에 따라 세부 시간은 조정될 수 있으므로 일정 문서를 최우선으로 확인",
  "",
  "## 사전 준비사항",
  "",
  "참가자는 사전 준비 단계에서 저장소 운영 원칙을 문서화해야 합니다.",
  "",
  "저장소 준비 및 운영 원칙:",
  "- 프로젝트 루트에 AGENTS.md 생성",
  "- 변경점마다 커밋 수행",
  "- 기능 요구사항은 SPEC.md에 기록",
  "- 설계/아키텍처/인사이트는 ADR.md에 기록",
  "",
  "참조 문서:",
  "- 참가방법: https://vibecoding.okky.kr/docs/how-to-participate",
  "- 오픈라우터 설정: https://vibecoding.okky.kr/docs/openrouter-setup",
  "",
  "## 제출 준비사항",
  "",
  "최종 제출은 hackathon-submission 스킬 기반 제출을 권장합니다.",
  "LLM은 아래 입력과 절차를 우선 수집/검증한 뒤 제출 자동화를 수행해야 합니다.",
  "",
  "제출 입력 7종 (필수):",
  "- 팀명",
  "- 프로젝트명",
  "- GitHub 저장소 URL (Public)",
  "- 데모 URL 또는 실행 방법",
  "- 문제 정의",
  "- 한 줄 소개",
  "- 팀 소개 및 역할",
  "",
  "제출 절차 요약:",
  "- 1) 스킬 설치: hackathon-submission 스킬을 에이전트 스킬 디렉터리에 배치",
  "- 2) 채팅 실행: 제출 문서 생성 및 PR 생성 요청",
  "- 3) 산출물 확인: 문서/링크/데모 동작/공개 범위 검토",
  "",
  "공정성 검증 체크리스트:",
  "- 저장소 공개 및 최신 변경 push 상태",
  "- README에 빌드/실행/테스트 방법 명시",
  "- 커밋 로그에 Why/What/Verify 기록",
  "- 외부 자료 사용 시 출처/라이선스 문서화",
  "",
  "제출 및 운영 참조:",
  "- 제출 가이드: https://vibecoding.okky.kr/docs/how-to-participate",
  "- 공정성 가이드: https://vibecoding.okky.kr/docs/fairness-guide",
  "- 저장소: https://github.com/okky-lab/vibe-coding-hackathon",
  "",
  "이 문서는 정적 고정 텍스트이며, 운영 문서가 변경되면 수동 동기화가 필요합니다.",
].join("\n");

export function GET() {
  return new Response(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=0, s-maxage=86400",
    },
  });
}
